<p>title: Promise 对象<br>date: 2018.9.9<br>tags: </p>
<ul>
<li>ecmascript</li>
</ul>
<hr>
<p style="text-align:right">2018.9.9 星期日 23:51 </p>

<p>1. Promise 的含义<br>2. 基本用法<br>3. Promise.prototype.then()<br>4. Promise.prototype.catch()<br>5. Promise.prototype.finally()<br>6. Promise.all()<br>7. Promise.race()<br>8. Promise.resolve()<br>9. Promise.reject()<br>10. 应用<br>11. Promise.try()</p>
<!-- more -->
<h2 id="1-Promise-的含义"><a href="#1-Promise-的含义" class="headerlink" title="1 Promise 的含义"></a>1 Promise 的含义</h2><p>Promise 是异步编程的一种解决方案，比传统的解决方案——回调函数和事件——更合理和更强大。    </p>
<p>所谓Promise，简单说就是一个容器，里面保存着某个未来才会结束的事件（通常是一个异步操作）的结果。从语法上说，Promise 是一个对象，从它可以获取异步操作的消息。Promise 提供统一的 API，各种异步操作都可以用同样的方法进行处理。     </p>
<p>Promise对象有以下两个特点。<br>（1）对象的状态不受外界影响。Promise对象代表一个异步操作，有三种状态：pending（进行中）、fulfilled（已成功）和rejected（已失败）。只有异步操作的结果，可以决定当前是哪一种状态，任何其他操作都无法改变这个状态。<br>（2）一旦状态改变，就不会再变，任何时候都可以得到这个结果。Promise对象的状态改变，只有两种可能：从pending变为fulfilled和从pending变为rejected。   </p>
<p>优缺点：…  </p>
<p>如果某些事件不断地反复发生，一般来说，使用 Stream 模式是比部署Promise更好的选择。   </p>
<h2 id="2-基本用法"><a href="#2-基本用法" class="headerlink" title="2 基本用法"></a>2 基本用法</h2><p>ES6 规定，Promise对象是一个构造函数，用来生成Promise实例。<br>Promise实例生成以后，可以用then方法分别指定resolved状态和rejected状态的回调函数。<br>then方法可以接受两个回调函数作为参数。<br>第二个函数是可选的，不一定要提供。这两个函数都接受Promise对象传出的值作为参数。<br>Promise 新建后就会立即执行。    </p>
<p>resolve函数的参数除了正常的值以外，还可能是另一个 Promise 实例  </p>
<p>注意，调用resolve或reject并不会终结 Promise 的参数函数的执行。<br>一般来说，调用resolve或reject以后，Promise 的使命就完成了，后继操作应该放到then方法里面，而不应该直接写在resolve或reject的后面。所以，最好在它们前面加上return语句，这样就不会有意外。  </p>
<h2 id="3-Promise-prototype-then"><a href="#3-Promise-prototype-then" class="headerlink" title="3 Promise.prototype.then()"></a>3 Promise.prototype.then()</h2><p>then方法返回的是一个新的Promise实例（注意，不是原来那个Promise实例）。因此可以采用链式写法，即then方法后面再调用另一个then方法。        </p>
<h2 id="4-Promise-prototype-catch"><a href="#4-Promise-prototype-catch" class="headerlink" title="4 Promise.prototype.catch()"></a>4 Promise.prototype.catch()</h2><p>Promise.prototype.catch方法是.then(null, rejection)的别名，用于指定发生错误时的回调函数。   </p>
<p>如果 Promise 状态已经变成resolved，再抛出错误是无效的。     </p>
<p>Promise 对象的错误具有“冒泡”性质，会一直向后传递，直到被捕获为止。也就是说，错误总是会被下一个catch语句捕获。<br>上面代码中，一共有三个 Promise 对象：一个由getJSON产生，两个由then产生。它们之中任何一个抛出的错误，都会被最后一个catch捕获。   </p>
<p>一般来说，不要在then方法里面定义 Reject 状态的回调函数（即then的第二个参数），总是使用catch方法。       </p>
<p>跟传统的try/catch代码块不同的是，如果没有使用catch方法指定错误处理的回调函数，Promise 对象抛出的错误不会传递到外层代码，即不会有任何反应。      </p>
<p>catch方法返回的还是一个 Promise 对象，因此后面还可以接着调用then方法。<br>此时，要是then方法里面报错，就与前面的catch无关了。     </p>
<p>catch方法之中，还能再抛出错误。     </p>
<h2 id="5-Promise-prototype-finally"><a href="#5-Promise-prototype-finally" class="headerlink" title="5 Promise.prototype.finally()"></a>5 Promise.prototype.finally()</h2><p>该方法是 ES2018 引入标准的。<br>finally本质上是then方法的特例。   </p>
<h2 id="6-Promise-all"><a href="#6-Promise-all" class="headerlink" title="6 Promise.all()"></a>6 Promise.all()</h2><p>Promise.all方法接受一个数组作为参数，如果不是，就会先调用下面讲到的Promise.resolve方法，将参数转为 Promise 实例，再进一步处理。（Promise.all方法的参数可以不是数组，但必须具有 Iterator 接口，且返回的每个成员都是 Promise 实例。）    </p>
<p>p的状态由p1、p2、p3决定，分成两种情况。     </p>
<p>注意，如果作为参数的 Promise 实例，自己定义了catch方法，那么它一旦被rejected，并不会触发Promise.all()的catch方法。</p>
<h2 id="7-Promise-race"><a href="#7-Promise-race" class="headerlink" title="7 Promise.race()"></a>7 Promise.race()</h2><p>只要p1、p2、p3之中有一个实例率先改变状态，p的状态就跟着改变。那个率先改变的 Promise 实例的返回值，就传递给p的回调函数。     </p>
<p>下面是一个例子，如果指定时间内没有获得结果，就将 Promise 的状态变为reject，否则变为resolve。</p>
<pre><code class="javascript"><span class="keyword">const</span> p = <span class="built_in">Promise</span>.race([
  fetch(<span class="string">'/resource-that-may-take-a-while'</span>),
  <span class="keyword">new</span> <span class="built_in">Promise</span>(<span class="function"><span class="keyword">function</span> (<span class="params">resolve, reject</span>) </span>{
    setTimeout(<span class="function"><span class="params">()</span> =&gt;</span> reject(<span class="keyword">new</span> <span class="built_in">Error</span>(<span class="string">'request timeout'</span>)), <span class="number">5000</span>)
  })
]);

p
.then(<span class="built_in">console</span>.log)
.catch(<span class="built_in">console</span>.error);
</code></pre>
<h2 id="8-Promise-resolve"><a href="#8-Promise-resolve" class="headerlink" title="8 Promise.resolve()"></a>8 Promise.resolve()</h2><p>有时需要将现有对象转为 Promise 对象，Promise.resolve方法就起到这个作用。        </p>
<p>Promise.resolve方法的参数分成四种情况。<br>（1）参数是一个 Promise 实例<br>（2）参数是一个thenable对象<br>（3）参数不是具有then方法的对象，或根本就不是对象<br>（4）不带有任何参数     </p>
<p>需要注意的是，立即resolve的 Promise 对象，是在本轮“事件循环”（event loop）的结束时，而不是在下一轮“事件循环”的开始时。      </p>
<pre><code class="javascript">setTimeout(<span class="function"><span class="keyword">function</span> (<span class="params"></span>) </span>{
  <span class="built_in">console</span>.log(<span class="string">'three'</span>);
}, <span class="number">0</span>);
<span class="built_in">Promise</span>.resolve().then(<span class="function"><span class="keyword">function</span> (<span class="params"></span>) </span>{
  <span class="built_in">console</span>.log(<span class="string">'two'</span>);
});
<span class="built_in">console</span>.log(<span class="string">'one'</span>);
<span class="comment">// one</span>
<span class="comment">// two</span>
<span class="comment">// three</span>
</code></pre>
<h2 id="9-Promise-reject"><a href="#9-Promise-reject" class="headerlink" title="9 Promise.reject()"></a>9 Promise.reject()</h2><p>注意，Promise.reject()方法的参数，会原封不动地作为reject的理由，变成后续方法的参数。这一点与Promise.resolve方法不一致。     </p>
<p>上面代码中，Promise.reject方法的参数是一个thenable对象，执行以后，后面catch方法的参数不是reject抛出的“出错了”这个字符串，而是thenable对象。</p>
<h2 id="10-应用"><a href="#10-应用" class="headerlink" title="10 应用"></a>10 应用</h2><h3 id="加载图片"><a href="#加载图片" class="headerlink" title="加载图片"></a>加载图片</h3><h3 id="Generator-函数与-Promise-的结合"><a href="#Generator-函数与-Promise-的结合" class="headerlink" title="Generator 函数与 Promise 的结合"></a>Generator 函数与 Promise 的结合</h3><h2 id="11-Promise-try"><a href="#11-Promise-try" class="headerlink" title="11 Promise.try()"></a>11 Promise.try()</h2><p>提案：chrome也没有通过      </p>
<p>下面的写法有一个缺点，就是如果f是同步函数，那么它会在本轮事件循环的末尾执行。函数f是同步的，但是用 Promise 包装了以后，就变成异步执行了。   </p>
<pre><code class="javascript"><span class="keyword">const</span> f = <span class="function"><span class="params">()</span> =&gt;</span> <span class="built_in">console</span>.log(<span class="string">'now'</span>);
<span class="built_in">Promise</span>.resolve().then(f);
<span class="built_in">console</span>.log(<span class="string">'next'</span>);
<span class="comment">// next</span>
<span class="comment">// now</span>
</code></pre>
<p>回答是可以的，并且还有两种写法。第一种写法是用async函数来写。<br>第二种写法是使用new Promise()。<br><code>`</code>javascriptconst f = () =&gt; console.log(‘now’);<br>Promise.try(f);<br>console.log(‘next’);<br>// now<br>// next</p>
<pre><code>
事实上，Promise.try存在已久，Promise 库Bluebird、Q和when，早就提供了这个方法。  
由于Promise.try为所有操作提供了统一的处理机制，所以如果想用then方法管理流程，最好都用Promise.try包装一下。这样有许多好处，其中一点就是可以更好地管理异常。  

但是database.users.get()可能还会抛出同步错误（比如数据库连接错误，具体要看实现方法），这时你就不得不用try...catch去捕获。       
事实上，Promise.try就是模拟try代码块，就像promise.catch模拟的是catch代码块。   
```javascript
    Promise.try(database.users.get({id: userId}))
    .then(...)
    .catch(...)
</code></pre><p style="text-align:right">00:30</p>

